---
version: 2
updates:
  - package-ecosystem: docker
    directory: /
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: monthly
